CREATE USER admin2
IDENTIFIED BY p4ssw0rdy
DEFAULT TABLESPACE users
TEMPORARY TABLESPACE temp
QUOTA 10M ON users;

GRANT connect to Project0;
GRANT resource to Project0;
GRANT create session TO Project0;
GRANT create table TO Project0;
GRANT create view TO Project0;

conn admin2/p4ssw0rdy

DROP TABLE BANK_USERS;
DROP TABLE ACCOUNTS;
DROP TABLE TRANSACTIONS;
DROP TABLE CONTACT;

CREATE TABLE BANK_USERS(
    USER_ID INTEGER PRIMARY KEY,
    USER_NAME VARCHAR2(20) NOT NULL,
    PASWORD VARCHAR2(20) NOT NULL,
    USER_TYPE INTEGER DEFAULT 0,
    FIRST_NAME VARCHAR2(50) NOT NULL,
    LAST_NAME VARCHAR2(50) NOT NULL
);
/
ALTER TABLE BANK_USERS
 ADD CONSTRAINT USER_TYPE_D DEFAULT 0 REFERENCES BANK_USERS(USER_TYPE);

CREATE TABLE ACCOUNTS(
    ACCOUNT_ID INTEGER PRIMARY KEY,
    BALANCE NUMBER(10,2),
    USER_ID INTEGER NOT NULL
);
/
ALTER TABLE ACCOUNTS
    ADD CONSTRAINT FK_ACCOUNTS_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES BANK_USERS(USER_ID);
/
CREATE TABLE TRANSACTIONS(
    TRANSACTION_ID INTEGER PRIMARY KEY,
    TRANSACTION_TYPE INTEGER NOT NULL,
    TRANSACTION_AMT NUMBER(10,2),
    ACCOUNT_ID INTEGER NOT NULL
);
/
ALTER TABLE TRANSACTIONS
    ADD CONSTRAINT FK_TRANSACTIONS_ACCOUNT_ID
    FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNTS(ACCOUNT_ID);
/
CREATE TABLE CONTACT(
    PHONE INTEGER PRIMARY KEY,
    USER_ID INTEGER,
    EMAIL VARCHAR2(50),
    STREET_ADDRESS VARCHAR2(50),
    ZIPCODE INTEGER,
    REGION VARCHAR2(15)
);
/
ALTER TABLE CONTACT
    ADD CONSTRAINT FK_CONTACT_USER_ID
    FOREIGN KEY (USER_ID) REFERENCES BANK_USERS (USER_ID);
    /
    
INSERT ALL INTO BANK_USERS
  VALUES(1, 'TheBoss', 'Password', 1, 'Tucker', 'Belton')
  SELECT * FROM DUAL;
  
INSERT ALL INTO BANK_USERS
 VALUES(2,'TheOtherBoss', 'P455w0rd',1,'Silvia','Garcia')
 SELECT * FROM DUAL;
 
CREATE SEQUENCE SQ_USER_ID_PK
START WITH 3
INCREMENT BY 1;
/
CREATE OR REPLACE TRIGGER TR_INSERT_USER
BEFORE INSERT ON BANK_USERS
FOR EACH ROW
BEGIN
    SELECT SQ_USER_ID_PK.NEXTVAL INTO :NEW.USER_ID FROM DUAL;
END;
/
CREATE SEQUENCE SQ_ACCOUNT_ID_PK
START WITH 1
INCREMENT BY 1;
/

CREATE OR REPLACE TRIGGER TR_CREATE_ACCOUNTS
BEFORE INSERT ON ACCOUNTS
FOR EACH ROW
BEGIN
    SELECT SQ_ACCOUNT_ID_PK.NEXTVAL INTO :NEW.ACCOUNT_ID FROM DUAL;
END;
/

INSERT INTO BANK_USERS (USER_NAME, PASWORD, FIRST_NAME, LAST_NAME)
 VALUES ('ClientOne', 'CPassw0rd', 'Ottern','Bearly');
/
SELECT * FROM BANK_USERS;



   
    
